defaults:
  - _self_
  - override hydra/sweeper: optuna

model:
  input_size: 784
  num_classes: 10

data:
  batch_size: 64
  data_dir: ./data
  num_workers: 4

training:
  seed: 42
  learning_rate: 0.001
  weight_decay: 0.0001
  max_lr: 0.01
  num_epochs: 200
  accelerator: auto
  devices: 1
  deterministic: true
  enable_progress_bar: true
  gradient_clip_val: 0.5
  accumulate_grad_batches: 1
  precision: 32
  val_check_interval: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0

  early_stopping:
    enable: true
    monitor: val_loss
    mode: min
    patience: 3
    verbose: true

  checkpointing:
    enable: true
    filename: best-checkpoint
    monitor: val_loss
    mode: min
    save_top_k: 1
    save_last: true
    verbose: true

wandb:
  project: fashion_mnist
  run_name: baseline_run
  tags: [optuna, sweep]
  notes: "Optuna hyperparameter sweep"
  log_model: true

paths:
  log_dir: ./logs
  checkpoint_dir: ./checkpoints

logging:
  log_every_n_steps: 10

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
    direction: maximize
    study_name: fashion_mnist_optuna
    n_trials: 100
    n_jobs: 1
    search_space:
      training.learning_rate:
        type: float
        low: 0.0001
        high: 0.01
        log: true
      training.weight_decay:
        type: float
        low: 0.00001
        high: 0.001
        log: true
      training.max_lr:
        type: float
        low: 0.01
        high: 0.1