data:
  batch_size: 512
  data_dir: "datasets/"
  num_workers: 4

model:
  input_size: 784
  num_classes: 10

training:
  num_epochs: 250
  learning_rate: 0.0001
  weight_decay: 1e-4
  max_lr: 0.01
  patience: 15
  seed: 42

paths:
  data_dir: datasets/
  checkpoint_dir: checkpoints/
  log_dir: logs/
  results_dir: results/


logging:
  log_every_n_steps: 50
  save_top_k: 3