training_cycles: 10

data:
  batch_size: [32, 64, 128]
  data_dir: "./data"

model:
  input_size: 784
  num_classes: 10

training:
  learning_rate: [0.0001, 0.001, 0.01]
  weight_decay: [0.0, 0.01, 0.001]
  max_lr: [0.01, 0.1]
  num_epochs: 10
  patience: 3
  seed: 42

paths:
  log_dir: "./logs"

logging:
  log_every_n_steps: 10